### ISSUE TITLE
Keep being unable to render the webview with this error

### ISSUE THREAD

**Issue by 34code** [hotwired/hotwire-native-ios#51]
I have a tabbed app, and am continuously getting the following error on load:

```
Failed to resolve host network app id to config: bundleID: com.apple.WebKit.Networking instance ID: Optional([_EXExtensionInstanceIdentifier: E4ED32DE-2380-44CF-A3F4-29B4D5AE083F])
```

I've tried setting the userAgent to a custom user agent (described here: https://forums.developer.apple.com/forums/thread/762223) and still no luck.. I'm running iOS 18.1 and tested on 18.1 and 18.2

**Comment by 34code** [comment]
More context: 

This is an existing project which stopped working after updating to Sequoia 15.2. It was working before on Sonoma. The `hotwire-native-ios` still works out of the box, but my existing app stopped working.

**Comment by joemasilotti** [comment]
That error shouldn't cause the web view to fail. Is your server receiving the request? What's the response code?

**Comment by 34code** [comment]
Yes server (when I set to "local") is receiving the request. However it does not return a 500 code but the app still believes an error occurred and gives this message for all tabs. 

<img width="568" alt="Screenshot 2024-12-01 at 4 45 05 PM" src="https://github.com/user-attachments/assets/ff6ffa5f-a863-47af-84a1-a01def1722b4">

Here is a screenshot of the logs while building the app in simulator:

<img width="562" alt="Screenshot 2024-12-01 at 4 46 17 PM" src="https://github.com/user-attachments/assets/046a28c1-24ed-4380-b23d-0926bddcf0c3">

**Comment by 34code** [comment]
full error log just now running it against "local".

```
[Session] visit ["reload": false, "location": http://localhost:3002/m, "options": HotwireNative.VisitOptions(action: HotwireNative.VisitAction.advance, response: nil)]
[ColdBootVisit] startVisit http://localhost:3002/m
[Session] visit ["reload": false, "location": http://localhost:3002/m/ask, "options": HotwireNative.VisitOptions(action: HotwireNative.VisitAction.advance, response: nil)]
[ColdBootVisit] startVisit http://localhost:3002/m/ask
[Session] visit ["location": http://localhost:3002/m/orders, "options": HotwireNative.VisitOptions(action: HotwireNative.VisitAction.advance, response: nil), "reload": false]
[ColdBootVisit] startVisit http://localhost:3002/m/orders
[Session] visit ["location": http://localhost:3002/m/profile, "reload": false, "options": HotwireNative.VisitOptions(action: HotwireNative.VisitAction.advance, response: nil)]
[ColdBootVisit] startVisit http://localhost:3002/m/profile
[Bridge] bridgeDestinationViewDidLoad: http://localhost:3002/m
[Bridge] bridgeDestinationViewWillAppear: http://localhost:3002/m
Failed to request storage access quirks from WebPrivacy.
Failed to request storage access user agent string quirks from WebPrivacy.
[Bridge] bridgeDestinationViewDidAppear: http://localhost:3002/m
WebContent process (0x112018c40) took 1.027111 seconds to launch
WebContent process (0x112019200) took 1.116318 seconds to launch
WebContent process (0x1120197c0) took 1.282586 seconds to launch
WebContent process (0x112019d80) took 1.362063 seconds to launch
WebContent process (0x11201a340) took 1.460815 seconds to launch
WebContent process (0x11201a900) took 1.569177 seconds to launch
Failed to resolve host network app id to config: bundleID: com.apple.WebKit.Networking instance ID: Optional([_EXExtensionInstanceIdentifier: E504AC15-779C-49AB-894E-8EB09E2D9954])
WebContent process (0x11201aec0) took 1.648233 seconds to launch
WebContent process (0x11201b480) took 1.742717 seconds to launch
Networking process (0x112036b00) took 1.602770 seconds to launch
Failed to request query parameters from WebPrivacy.
Failed to request restricted opener domains from WebPrivacy
Failed to request allowed query parameters from WebPrivacy.
Failed to request allowed query parameters from WebPrivacy.
Error creating the CFMessagePort needed to communicate with PPT.
[Bridge] bridgeDestinationViewDidLoad: http://localhost:3002/m/ask
[ColdBootVisit] failVisit h
```
![Screenshot 2024-12-01 at 5 05 32 PM](https://github.com/user-attachments/assets/33ae4db7-1b46-42ec-89a1-844568178007)

**Comment by joemasilotti** [comment]
It looks like you either a) don't have Turbo.js exposed on server or b) are getting a 406. Can you share the server logs?

**Comment by 34code** [comment]
How do I check if Turbo.js is exposes on the server? Here are the server logs.. it says completed 200 OK..

```
18:04:22 web.1  | [ed3b04ad-96a0-41d5-8176-ed3a62f6824a] Started GET "/m" for ::1 at 2024-12-02 18:04:22 -0800
18:04:22 web.1  | [ed3b04ad-96a0-41d5-8176-ed3a62f6824a] Processing by MobileController#home as HTML
18:04:22 web.1  | [ed3b04ad-96a0-41d5-8176-ed3a62f6824a]   MvCatComAllStores Load (3.8ms)  SELECT "mv_cat_com_all_stores".* FROM "mv_cat_com_all_stores" /*action='home',application='Botflip',controller='mobile'*/
18:04:22 web.1  | [ed3b04ad-96a0-41d5-8176-ed3a62f6824a]   ↳ app/controllers/mobile_controller.rb:182:in `sort_by'
18:04:22 web.1  | [ed3b04ad-96a0-41d5-8176-ed3a62f6824a]   MvCatComWalmart Load (1.4ms)  SELECT "mv_cat_com_walmarts".* FROM "mv_cat_com_walmarts" /*action='home',application='Botflip',controller='mobile'*/
18:04:22 web.1  | [ed3b04ad-96a0-41d5-8176-ed3a62f6824a]   ↳ app/controllers/mobile_controller.rb:202:in `sort_by'
18:04:22 web.1  | [ed3b04ad-96a0-41d5-8176-ed3a62f6824a]   Rendering layout app/views_mobile/layouts/mobile.html.erb
18:04:22 web.1  | [ed3b04ad-96a0-41d5-8176-ed3a62f6824a]   Rendering app/views_mobile/mobile/home.html.erb within layouts/mobile
18:04:22 web.1  | [ed3b04ad-96a0-41d5-8176-ed3a62f6824a]   Rendered app/views_mobile/mobile/home.html.erb within layouts/mobile (Duration: 0.7ms | GC: 0.0ms)
18:04:22 web.1  | [ed3b04ad-96a0-41d5-8176-ed3a62f6824a]   Rendered layout app/views_mobile/layouts/mobile.html.erb (Duration: 8.1ms | GC: 3.8ms)
18:04:22 web.1  | [ed3b04ad-96a0-41d5-8176-ed3a62f6824a] Completed 200 OK in 103ms (Views: 8.9ms | ActiveRecord: 5.2ms (2 queries, 0 cached) | GC: 4.9ms)
18:04:22 web.1  |
18:04:22 web.1  |
18:04:23 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3] Started GET "/fp?fp=963702546&b=undefined&d=undefined&o=undefined&sr=393x852&c=undefined&ua=BotFlip%20App:%20iOS" for ::1 at 2024-12-02 18:04:23 -0800
18:04:23 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3] Processing by ApplicationController#grab_fingerprint as */*
18:04:23 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3]   Parameters: {"fp"=>"963702546", "b"=>"undefined", "d"=>"undefined", "o"=>"undefined", "sr"=>"393x852", "c"=>"undefined", "ua"=>"BotFlip App: iOS"}
18:04:23 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3]   Fingerprint Load (203.0ms)  SELECT "fingerprints".* FROM "fingerprints" WHERE "fingerprints"."fingerprint" = '963702546' ORDER BY "fingerprints"."id" ASC LIMIT 1 /*action='grab_fingerprint',application='Botflip',controller='application'*/
18:04:23 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3]   ↳ app/controllers/application_controller.rb:275:in `grab_fingerprint'
18:04:23 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3]   TRANSACTION (187.5ms)  BEGIN /*action='grab_fingerprint',application='Botflip',controller='application'*/
18:04:23 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3]   ↳ app/controllers/application_controller.rb:277:in `grab_fingerprint'
18:04:23 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3]   Account Load (384.8ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."id" = 0 LIMIT 1 /*action='grab_fingerprint',application='Botflip',controller='application'*/
18:04:23 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3]   ↳ app/controllers/application_controller.rb:277:in `grab_fingerprint'
18:04:24 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3]   TRANSACTION (192.6ms)  ROLLBACK /*action='grab_fingerprint',application='Botflip',controller='application'*/
18:04:24 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3]   ↳ app/controllers/application_controller.rb:277:in `grab_fingerprint'
18:04:24 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3]   Rendering application/grab_fingerprint.html.erb
18:04:24 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3]   Rendered application/grab_fingerprint.html.erb (Duration: 0.1ms | GC: 0.0ms)
18:04:24 web.1  | [a44dfb76-c306-467e-b8e2-d3b05ab971e3] Completed 200 OK in 863ms (Views: 0.4ms | ActiveRecord: 967.8ms (2 queries, 0 cached) | GC: 0.3ms)
18:04:24 web.1  |
18:04:24 web.1  |
```

**Comment by 34code** [comment]
I'm going to try modifying a vanilla `hotwire-native-ios` app and point it to my server and report back if any errors are found.

**Comment by joemasilotti** [comment]
Logs look OK! You could try `Turbo` in the web debug console and see what happens.

**Comment by 34code** [comment]
You were right! It is indeed turbo not loading.. something amiss in my importmaps.. Will try to figure out how to get it back... Thanks for pointing me in the right direction!
